/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuGuias;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Jose De Avila
 */
public class Guia26 extends javax.swing.JFrame {

    JButton vButtons[];
    
    public Guia26() {
        initComponents();
        crearVentana();
    }
    
    public void crearVentana(){
        vButtons = new JButton[5];
        this.setTitle("Ejemplo de vectores y eventos");
        this.setSize(600,200);
        
        String textoBotones[] = {"Aceptar", "Cancelar", "Aplicar", "Cerrar", "Salir"};
        
        for(int i=0; i<vButtons.length;i++){
            vButtons[i] = new JButton();
            vButtons[i].setText(textoBotones[i]);
            vButtons[i].setBounds(10+i*100, 50, 90, 20);
            this.getContentPane().add(vButtons[i]);
        }
        for(int i=0; i<vButtons.length; i++){
            vButtons[i].addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent evt){
                    botonesActionPerformed(evt);
                }
            });
        }
        JButton btn = new JButton();
        btn.setText("Volver");
        btn.setBounds(10, 130, 90, 20);
        this.getContentPane().add(btn);
        btn.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                btnActionPerformed(evt);
            }
        });
    }
    
    public void btnActionPerformed(ActionEvent evt){
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        this.dispose();
    }
    
    public void botonesActionPerformed(ActionEvent evt){
        JButton botonPulsado = (JButton) evt.getSource();
        JOptionPane.showMessageDialog(null, "Has pulsado el boton: "+botonPulsado.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guia26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guia26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guia26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guia26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guia26().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
