/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuGuias;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose De Avila
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guia3 = new javax.swing.JButton();
        guia2 = new javax.swing.JButton();
        guia1 = new javax.swing.JButton();
        guia4 = new javax.swing.JButton();
        guia5 = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        guia6 = new javax.swing.JButton();
        guia7 = new javax.swing.JButton();
        guia8 = new javax.swing.JButton();
        guia9 = new javax.swing.JButton();
        guia10 = new javax.swing.JButton();
        guia11 = new javax.swing.JButton();
        guia12 = new javax.swing.JButton();
        guia13 = new javax.swing.JButton();
        guia14 = new javax.swing.JButton();
        guia15 = new javax.swing.JButton();
        guia16 = new javax.swing.JButton();
        guia17 = new javax.swing.JButton();
        guia18 = new javax.swing.JButton();
        guia19 = new javax.swing.JButton();
        guia20 = new javax.swing.JButton();
        guia21 = new javax.swing.JButton();
        guia22 = new javax.swing.JButton();
        guia23 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel1.setText("Guias Disponibles");

        guia3.setBackground(new java.awt.Color(0, 0, 204));
        guia3.setForeground(new java.awt.Color(255, 255, 255));
        guia3.setText("Guia 3");
        guia3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia3MouseClicked(evt);
            }
        });

        guia2.setBackground(new java.awt.Color(0, 0, 204));
        guia2.setForeground(new java.awt.Color(255, 255, 255));
        guia2.setText("Guia 2");
        guia2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia2MouseClicked(evt);
            }
        });

        guia1.setBackground(new java.awt.Color(0, 0, 204));
        guia1.setForeground(new java.awt.Color(255, 255, 255));
        guia1.setText("Guia 1");
        guia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia1MouseClicked(evt);
            }
        });
        guia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia1ActionPerformed(evt);
            }
        });

        guia4.setBackground(new java.awt.Color(0, 0, 204));
        guia4.setForeground(new java.awt.Color(255, 255, 255));
        guia4.setText("Guia 4");
        guia4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia4MouseClicked(evt);
            }
        });

        guia5.setBackground(new java.awt.Color(0, 0, 204));
        guia5.setForeground(new java.awt.Color(255, 255, 255));
        guia5.setText("Guia 5");
        guia5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia5MouseClicked(evt);
            }
        });

        exit_button.setText("Salir");
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
        });

        guia6.setBackground(new java.awt.Color(0, 0, 204));
        guia6.setForeground(new java.awt.Color(255, 255, 255));
        guia6.setText("Guia 6");
        guia6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia6MouseClicked(evt);
            }
        });
        guia6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia6ActionPerformed(evt);
            }
        });

        guia7.setBackground(new java.awt.Color(0, 0, 204));
        guia7.setForeground(new java.awt.Color(255, 255, 255));
        guia7.setText("Guia 7");
        guia7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia7MouseClicked(evt);
            }
        });

        guia8.setBackground(new java.awt.Color(0, 0, 204));
        guia8.setForeground(new java.awt.Color(255, 255, 255));
        guia8.setText("Guia 8");
        guia8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia8MouseClicked(evt);
            }
        });
        guia8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia8ActionPerformed(evt);
            }
        });

        guia9.setBackground(new java.awt.Color(0, 0, 204));
        guia9.setForeground(new java.awt.Color(255, 255, 255));
        guia9.setText("Guia 9");
        guia9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia9MouseClicked(evt);
            }
        });

        guia10.setBackground(new java.awt.Color(0, 0, 204));
        guia10.setForeground(new java.awt.Color(255, 255, 255));
        guia10.setText("Guia 10");
        guia10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia10MouseClicked(evt);
            }
        });

        guia11.setBackground(new java.awt.Color(0, 0, 204));
        guia11.setForeground(new java.awt.Color(255, 255, 255));
        guia11.setText("Guia 11");
        guia11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia11MouseClicked(evt);
            }
        });

        guia12.setBackground(new java.awt.Color(0, 0, 204));
        guia12.setForeground(new java.awt.Color(255, 255, 255));
        guia12.setText("Guia 12");
        guia12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia12MouseClicked(evt);
            }
        });
        guia12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia12ActionPerformed(evt);
            }
        });

        guia13.setBackground(new java.awt.Color(0, 0, 204));
        guia13.setForeground(new java.awt.Color(255, 255, 255));
        guia13.setText("Guia 13");
        guia13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia13MouseClicked(evt);
            }
        });
        guia13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia13ActionPerformed(evt);
            }
        });

        guia14.setBackground(new java.awt.Color(0, 0, 204));
        guia14.setForeground(new java.awt.Color(255, 255, 255));
        guia14.setText("Guia 14");
        guia14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia14MouseClicked(evt);
            }
        });

        guia15.setBackground(new java.awt.Color(0, 0, 204));
        guia15.setForeground(new java.awt.Color(255, 255, 255));
        guia15.setText("Guia 15");
        guia15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia15MouseClicked(evt);
            }
        });
        guia15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia15ActionPerformed(evt);
            }
        });

        guia16.setBackground(new java.awt.Color(0, 0, 204));
        guia16.setForeground(new java.awt.Color(255, 255, 255));
        guia16.setText("Guia 16");
        guia16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia16MouseClicked(evt);
            }
        });

        guia17.setBackground(new java.awt.Color(0, 0, 204));
        guia17.setForeground(new java.awt.Color(255, 255, 255));
        guia17.setText("Guia 17");
        guia17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia17MouseClicked(evt);
            }
        });

        guia18.setBackground(new java.awt.Color(0, 0, 204));
        guia18.setForeground(new java.awt.Color(255, 255, 255));
        guia18.setText("Guia 18");
        guia18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia18MouseClicked(evt);
            }
        });

        guia19.setBackground(new java.awt.Color(0, 0, 204));
        guia19.setForeground(new java.awt.Color(255, 255, 255));
        guia19.setText("Guia 19");
        guia19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia19MouseClicked(evt);
            }
        });

        guia20.setBackground(new java.awt.Color(0, 0, 204));
        guia20.setForeground(new java.awt.Color(255, 255, 255));
        guia20.setText("Guia 20");
        guia20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia20MouseClicked(evt);
            }
        });
        guia20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia20ActionPerformed(evt);
            }
        });

        guia21.setBackground(new java.awt.Color(0, 0, 204));
        guia21.setForeground(new java.awt.Color(255, 255, 255));
        guia21.setText("Guia 22");
        guia21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia21MouseClicked(evt);
            }
        });
        guia21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia21ActionPerformed(evt);
            }
        });

        guia22.setBackground(new java.awt.Color(0, 0, 204));
        guia22.setForeground(new java.awt.Color(255, 255, 255));
        guia22.setText("Guia 25");
        guia22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia22ActionPerformed(evt);
            }
        });

        guia23.setBackground(new java.awt.Color(0, 0, 204));
        guia23.setForeground(new java.awt.Color(255, 255, 255));
        guia23.setText("Guia 26");
        guia23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guia23MouseClicked(evt);
            }
        });
        guia23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guia23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(exit_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guia2)
                            .addComponent(guia1)
                            .addComponent(guia3)
                            .addComponent(guia4)
                            .addComponent(guia5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(guia10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guia9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guia8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guia7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(guia6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(guia21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(guia12)
                                    .addComponent(guia11)
                                    .addComponent(guia13)
                                    .addComponent(guia14)
                                    .addComponent(guia15))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guia18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(guia19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(guia20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(guia17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(guia16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guia22)
                                .addGap(18, 18, 18)
                                .addComponent(guia23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guia11)
                    .addComponent(guia16)
                    .addComponent(guia6)
                    .addComponent(guia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guia12)
                    .addComponent(guia17)
                    .addComponent(guia7)
                    .addComponent(guia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guia18)
                    .addComponent(guia13)
                    .addComponent(guia8)
                    .addComponent(guia3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guia14)
                    .addComponent(guia19)
                    .addComponent(guia9)
                    .addComponent(guia4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guia15)
                    .addComponent(guia20)
                    .addComponent(guia10)
                    .addComponent(guia5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guia21)
                    .addComponent(guia22)
                    .addComponent(guia23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        int op = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la aplicación?", "¿Desea salir?", JOptionPane.YES_NO_OPTION);
         if (op == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else if (op==JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Aja hp, cual es tu maricá, ¿te vas o no?");
        }
        
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void guia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia1MouseClicked
        
    }//GEN-LAST:event_guia1MouseClicked

    private void guia2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia2MouseClicked
        Option_Buttons Option_Buttons = new Option_Buttons();
        Option_Buttons.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia2MouseClicked

    private void guia3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia3MouseClicked
        Combined_Squareds Combined_Squareds = new Combined_Squareds();
        Combined_Squareds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia3MouseClicked

    private void guia4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia4MouseClicked
        Guia4 Guia4 = new Guia4();
        Guia4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia4MouseClicked

    private void guia5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia5MouseClicked
        Guia5 Guia5 = new Guia5();
        Guia5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia5MouseClicked

    private void guia6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia6MouseClicked
        Guia6 Guia6 = new Guia6();
        Guia6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia6MouseClicked

    private void guia7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia7MouseClicked
        Guia_7 g7 = new Guia_7();
        g7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia7MouseClicked

    private void guia8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia8MouseClicked
        Guia_8 g8 = new Guia_8();
        g8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia8MouseClicked

    private void guia9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia9MouseClicked
        Guia_9 g9 = new Guia_9();
        g9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia9MouseClicked

    private void guia10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia10MouseClicked
        Guia10 g10 = new Guia10();
        g10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia10MouseClicked

    private void guia8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guia8ActionPerformed

    private void guia11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia11MouseClicked
        Guia11 g11 = new Guia11();
        g11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia11MouseClicked

    private void guia12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia12MouseClicked
        // Nothing
    }//GEN-LAST:event_guia12MouseClicked

    private void guia13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia13MouseClicked
        Guia13 g13 = new Guia13();
        g13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia13MouseClicked

    private void guia14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia14MouseClicked
        Guia14 g14 = new Guia14();
        g14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia14MouseClicked

    private void guia15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia15MouseClicked
        Guia15 g15 = new Guia15();
        g15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia15MouseClicked

    private void guia15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guia15ActionPerformed

    private void guia16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia16MouseClicked
        Parking g16 = new Parking();
        g16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia16MouseClicked

    private void guia17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia17MouseClicked
        Guia17 g17 = new Guia17();
        g17.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia17MouseClicked

    private void guia18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia18MouseClicked
        Guia18 g18 = new Guia18();
        g18.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia18MouseClicked

    private void guia19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia19MouseClicked
        Guia19 g19 = new Guia19();
        g19.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia19MouseClicked

    private void guia20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia20MouseClicked
        Guia20 g20 = new Guia20();
        g20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia20MouseClicked

    private void guia20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guia20ActionPerformed

    private void guia6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guia6ActionPerformed

    private void guia12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia12ActionPerformed
        Guia12 g12 = new Guia12();
        g12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia12ActionPerformed

    private void guia13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guia13ActionPerformed

    private void guia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia1ActionPerformed
        verification_requareds vr = new verification_requareds();
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia1ActionPerformed

    private void guia21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guia21MouseClicked

    private void guia21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia21ActionPerformed
        Guia22 g22 = new Guia22();
        g22.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia21ActionPerformed

    private void guia22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia22ActionPerformed
        Guia25 g25 = new Guia25();
        g25.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia22ActionPerformed

    private void guia23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guia23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guia23MouseClicked

    private void guia23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guia23ActionPerformed
        Guia26 g26 = new Guia26();
        g26.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guia23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_button;
    private javax.swing.JButton guia1;
    private javax.swing.JButton guia10;
    private javax.swing.JButton guia11;
    private javax.swing.JButton guia12;
    private javax.swing.JButton guia13;
    private javax.swing.JButton guia14;
    private javax.swing.JButton guia15;
    private javax.swing.JButton guia16;
    private javax.swing.JButton guia17;
    private javax.swing.JButton guia18;
    private javax.swing.JButton guia19;
    private javax.swing.JButton guia2;
    private javax.swing.JButton guia20;
    private javax.swing.JButton guia21;
    private javax.swing.JButton guia22;
    private javax.swing.JButton guia23;
    private javax.swing.JButton guia3;
    private javax.swing.JButton guia4;
    private javax.swing.JButton guia5;
    private javax.swing.JButton guia6;
    private javax.swing.JButton guia7;
    private javax.swing.JButton guia8;
    private javax.swing.JButton guia9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
